sudo: required
language: php
services:
  - docker

php:
    - 5.6
    - 7.0
    - hhvm

before_script:
    - composer self-update
install:
    - composer require --no-update squizlabs/php_codesniffer
    - composer install --prefer-source
script:
    - vendor/bin/phpcs --standard=psr2 src/
    - vendor/bin/phpunit --coverage-clover=clover.xml
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover clover.xml
    - if [[ $DEPLOY_DOCS == "true" ]]; then echo "Preparing to build and deploy documentation" ; make docs_build ; echo "Completed deploying documentation" ; fi

notifications:
    irc: irc.freenode.org#pennyphp
    email: false

matrix:
    fast_finish: true
    include:
      - php: 5.6
        env:
            - DEPLOY_DOCS=true
    exclude:
      - php: 5.6
        env:
            - DEPLOY_DOCS=false

cache:
    directories:
        - $HOME/.composer/cache

env:
  global:
    secure: Riiy2L3iua0Olm3Z1qtzqAAyqRA9YshyTjBB+77tJLSiuPmXNgFCKQRVg4kxCC5UnvF9A+Rv/W0DzUYQ+5O/0XVAGCqpndUJUNCBpwYYjQfWZ7jJyHnGqaKWDwXg3DW6dKlOTJa2xk0M5+BpqE3aAZlwnVeljMbzHSEJ/s1inCg=
