language: php

php:
    - 5.6
    - 7.0
    - hhvm

before_script:
    - composer self-update
install:
    - composer require --no-update squizlabs/php_codesniffer
    - composer install --prefer-source
script:
    - vendor/bin/phpcs --standard=psr2 src/
    - vendor/bin/phpunit --coverage-clover=clover.xml
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover clover.xml

notifications:
    irc: irc.freenode.org#pennyphp
    email: false

cache:
    directories:
        - $HOME/.composer/cache
